export const WMO = {
    0: { en: 'Clear sky', uk: 'Ясно' },
    1: { en: 'Mainly clear', uk: 'Переважно ясно' },
    2: { en: 'Partly cloudy', uk: 'Мінлива хмарність' },
    3: { en: 'Overcast', uk: 'Похмуро' },
    45: { en: 'Fog', uk: 'Туман' },
    48: { en: 'Depositing rime fog', uk: 'Паморозь' },
    51: { en: 'Light drizzle', uk: 'Легкий мряка' },
    53: { en: 'Moderate drizzle', uk: 'Мряка' },
    55: { en: 'Dense drizzle', uk: 'Сильна мряка' },
    56: { en: 'Light freezing drizzle', uk: 'Легкий паморозний дощ' },
    57: { en: 'Dense freezing drizzle', uk: 'Сильний паморозний дощ' },
    61: { en: 'Slight rain', uk: 'Невеликий дощ' },
    63: { en: 'Moderate rain', uk: 'Дощ' },
    65: { en: 'Heavy rain', uk: 'Сильний дощ' },
    66: { en: 'Light freezing rain', uk: 'Невеликий крижаних дощ' },
    67: { en: 'Heavy freezing rain', uk: 'Сильний крижаних дощ' },
    71: { en: 'Slight snow fall', uk: 'Невеликий сніг' },
    73: { en: 'Moderate snow fall', uk: 'Сніг' },
    75: { en: 'Heavy snow fall', uk: 'Сильний сніг' },
    77: { en: 'Snow grains', uk: 'Сніжна крупа' },
    80: { en: 'Rain showers: slight', uk: 'Короткочасні дощі: слабкі' },
    81: { en: 'Rain showers: moderate', uk: 'Короткочасні дощі: помірні' },
    82: { en: 'Rain showers: violent', uk: 'Зливи: сильні' },
    85: { en: 'Snow showers: slight', uk: 'Снігопад: слабкий' },
    86: { en: 'Snow showers: heavy', uk: 'Снігопад: сильний' },
    95: { en: 'Thunderstorm', uk: 'Гроза' },
    96: { en: 'Thunderstorm with slight hail', uk: 'Гроза з невеликим градом' },
    99: { en: 'Thunderstorm with heavy hail', uk: 'Гроза з сильним градом' },
};

export const ICON_BY_WMO = {
    0: 'sunny-day-16458.svg',
    1: 'sun-and-blue-cloud-16460.svg',
    2: 'blue-clouds-and-sun-16461.svg',
    3: 'cloudy-weather-16459.svg',
    45: 'fog-svgrepo-com',
    51: 'rainy-day-16464.svg',
    55: 'rainy-day-16464.svg',
    56: 'rainy-day-16464.svg',
    57: 'downpour-rain-and-blue-cloud-16463.svg',
    61: 'rainy-day-16464.svg',
    63: 'rainy-day-and-blue-cloud-16462.svg',
    65: 'downpour-rain-and-blue-cloud-16463.svg',
    66: 'hail-and-winter-cloud-16490.svg',
    67: 'hail-and-blue-cloud-16491.svg',
    71: 'winter-snowfall-16473.svg',
    73: 'winter-snowfall-16473.svg',
    75: 'snowy-weather-16472.svg',
    77: 'winter-snowfall-16473.svg',
    80: 'rainy-day-16464.svg',
    81: 'rainy-day-16464.svg',
    82: 'downpour-rain-and-blue-cloud-16463.svg',
    85: 'winter-snowfall-16473.svg',
    86: 'snowy-weather-16472.svg',
    95: 'thunder.svg',
    96: 'lightning-and-rainy-weather-16465.svg',
    99: 'lightning-and-rainy-weather-16465.svg',
};

export const weatherText = (code, lang) => (WMO[code]?.[lang]) || String(code);